### ISSUE TITLE
Please help me, I'm desperate 

### ISSUE THREAD

**Issue by AridamiMartin** [am-silex/anki_cambridge#26]
I don't know how many videos I've already seen or post to figure out how to copy the cookie of my profile at Cambridge. Please, would you be available to write a guideline or at least a video. Thanks!

**Comment by am-silex** [comment]
Hi!
You know, the problem is with my version of authentication. I wasn't able to implement proper login mechanism with username&password as I'm not a web developer. Unfortunately, no one has come forward since this addon was released. 

Cookie for current session could be easily found in Network tab in Chrome or FIrefox Developer mode (F12)
![image](https://user-images.githubusercontent.com/3120820/228509780-c97dcb59-e581-492e-baf9-59d61a205076.png)

**Comment by AridamiMartin** [comment]
Thanks!

I figured out how to do it yesterday night , but check out this ....

Even when the cookie is up to date and it's my own vocabulary list, this message keeps appearing ...

Sorry for bothering!

![image](https://user-images.githubusercontent.com/129211371/228584758-a595b826-1463-431b-8c20-1c161d73b9c8.png)

**Comment by ChristianAvila** [comment]
It looks like the authentication is working fine, but after the plugin fetches the words from a list, it removes them. Ensure that the ID you are using, you are the owner.

**Comment by am-silex** [comment]
In the latest update @ChristianAvila added native login process. Try it out!
